/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AppColor, AppRadius, AppSize } from "./design-system/theme";
import { IconName } from "./icons";
export { AppColor, AppRadius, AppSize } from "./design-system/theme";
export { IconName } from "./icons";
export namespace Components {
    interface DsButton {
        /**
          * @default 'primary'
         */
        "color": AppColor;
        /**
          * @default false
         */
        "disabled": boolean;
        /**
          * @default 'md'
         */
        "radius": AppRadius;
        /**
          * @default 'md'
         */
        "size": AppSize;
        /**
          * @default 'button'
         */
        "type": 'button' | 'submit' | 'reset';
        /**
          * @default 'solid'
         */
        "variant": 'solid' | 'outline' | 'ghost' | 'soft' | 'link';
    }
    interface DsIcon {
        /**
          * @default 'default'
         */
        "color": AppColor;
        "iconName": IconName;
        /**
          * @default 'md'
         */
        "iconSize": AppSize;
    }
    interface ForTesting {
    }
    interface ThemeSwitcher {
    }
}
declare global {
    interface HTMLDsButtonElement extends Components.DsButton, HTMLStencilElement {
    }
    var HTMLDsButtonElement: {
        prototype: HTMLDsButtonElement;
        new (): HTMLDsButtonElement;
    };
    interface HTMLDsIconElement extends Components.DsIcon, HTMLStencilElement {
    }
    var HTMLDsIconElement: {
        prototype: HTMLDsIconElement;
        new (): HTMLDsIconElement;
    };
    interface HTMLForTestingElement extends Components.ForTesting, HTMLStencilElement {
    }
    var HTMLForTestingElement: {
        prototype: HTMLForTestingElement;
        new (): HTMLForTestingElement;
    };
    interface HTMLThemeSwitcherElement extends Components.ThemeSwitcher, HTMLStencilElement {
    }
    var HTMLThemeSwitcherElement: {
        prototype: HTMLThemeSwitcherElement;
        new (): HTMLThemeSwitcherElement;
    };
    interface HTMLElementTagNameMap {
        "ds-button": HTMLDsButtonElement;
        "ds-icon": HTMLDsIconElement;
        "for-testing": HTMLForTestingElement;
        "theme-switcher": HTMLThemeSwitcherElement;
    }
}
declare namespace LocalJSX {
    interface DsButton {
        /**
          * @default 'primary'
         */
        "color"?: AppColor;
        /**
          * @default false
         */
        "disabled"?: boolean;
        /**
          * @default 'md'
         */
        "radius"?: AppRadius;
        /**
          * @default 'md'
         */
        "size"?: AppSize;
        /**
          * @default 'button'
         */
        "type"?: 'button' | 'submit' | 'reset';
        /**
          * @default 'solid'
         */
        "variant"?: 'solid' | 'outline' | 'ghost' | 'soft' | 'link';
    }
    interface DsIcon {
        /**
          * @default 'default'
         */
        "color"?: AppColor;
        "iconName": IconName;
        /**
          * @default 'md'
         */
        "iconSize"?: AppSize;
    }
    interface ForTesting {
    }
    interface ThemeSwitcher {
    }
    interface IntrinsicElements {
        "ds-button": DsButton;
        "ds-icon": DsIcon;
        "for-testing": ForTesting;
        "theme-switcher": ThemeSwitcher;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ds-button": LocalJSX.DsButton & JSXBase.HTMLAttributes<HTMLDsButtonElement>;
            "ds-icon": LocalJSX.DsIcon & JSXBase.HTMLAttributes<HTMLDsIconElement>;
            "for-testing": LocalJSX.ForTesting & JSXBase.HTMLAttributes<HTMLForTestingElement>;
            "theme-switcher": LocalJSX.ThemeSwitcher & JSXBase.HTMLAttributes<HTMLThemeSwitcherElement>;
        }
    }
}
